version: '3'

services:
  astro:
    build:
      context: .  # This sets the build context to the current directory
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 on the container (nginx default)
    environment:
      - NODE_ENV=production
